//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-west-2_LPUSPJelt"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "5jl4u2el0jroj23b42nm0ahaos"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USWest2

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1p067rcd2s8o4fhse0an91c0mnkg8jjoj0pdiufffa9de1lk3hoa"
